/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyWebsite;

import java.util.ArrayList;
import java.util.Collections;
import java.util.function.BooleanSupplier;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean isEqualArrayListAndMeanIsBiggerElement(ArrayList<Integer> arr1, ArrayList<Integer> arr2, Double k){
        if(arr1 == null || arr2 == null)
            return false;
        Collections.sort(arr1);
        Collections.sort(arr2);
        for(int i = 0; i < arr1.size(); i++){
            if(arr1.get(i) != arr2.get(i))
                return false;
        }
        int count = 0;
        for(int i = 0; i < arr1.size(); i++){
            count += arr1.get(i);
        }
        if(count / arr1.size() > k)
            return true;
        return false;
    }
 
}
